# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: myblog CI
# on 表示触发actions的条件
on:
  push:
    branches: [main] #main分支在push的时候会触发
  pull_request:
    branches: [main] #main分支在PR的时候会触发

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest #nodejs执行的操作系统

    strategy:
      matrix:
        node-version: [16.x] #选择你需要的nodejs版本
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2 #拉取你的最新代码
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: 安装Python依赖
        run: pip install -r requirements.txt

      - name: 添加防火墙白名单
        run: |
          python3 scripts/firewall.py lighthouse add \
                 --secret-id   ${{ secrets.TENCENT_SECRETID }}   \
                 --secret-key  ${{ secrets.TENCENT_SECRETKEY }}  \
                 --instance-id ${{ secrets.TENCENT_INSTANCEID }} \
                 --region     ap-hongkong                        \
                 --port       ${{ secrets.PORT }}                \
                 --protocol   TCP                                \
                 --source     CurrentIP                          \
                 --action     ACCEPT                             \
                 --description "$(echo -n Github Action: `git rev-parse --short HEAD`)"

      - name: 使用 Node.js ${{ matrix.node-version }}开始搞事情
        uses: actions/setup-node@v2
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - name: "编译"
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
        run: npm run docs:build
      - name: 自动同步文件夹到我的服务器
        # You may pin to the exact commit or the version.
        # uses: wangyucode/sftp-upload-action@24f8bb83383dc39bed201ee5da01475e6c38c568
        uses: wangyucode/sftp-upload-action@v1.3.3
        with:
          host: ${{ secrets.SERVER_IP }} #你的nginx服务器公网ip
          port: "22" #你的nginx服务器ssh端口
          username: ${{ secrets.USERNAME }} #你的nginx服务器用户名
          password: ${{ secrets.PASSWORD }} #你的nginx服务器密码
          localDir: "dist" #你vue项目build好的文件的路径,每次服务器上会自动删除对应的文件夹后重新覆盖
          remoteDir: "/data1/web/" #你要把你build好的文件夹放到nginx服务器上的什么位置

      - name: 删除防火墙白名单
        run: |
          python3 scripts/firewall.py lighthouse remove \
                 --secret-id   ${{ secrets.TENCENT_SECRETID }}   \
                 --secret-key  ${{ secrets.TENCENT_SECRETKEY }}  \
                 --instance-id ${{ secrets.TENCENT_INSTANCEID }} \
                 --region     ap-hongkong                        \
                 --port       ${{ secrets.PORT }}                \
                 --protocol   TCP                                \
                 --action     ACCEPT                             \
                 --description "$(echo -n Github Action: `git rev-parse --short HEAD`)"
